[PRMT-1041] Add audit and canary pipelines - Split pipeline into separate files

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -2,13 +2,28 @@
 
 set -Eeo pipefail
 
+###########################
+# Local Config Parameters #
+###########################
+
 AWS_DEFAULT_REGION=eu-west-2
 IMAGE_REPO_NAME=deductions/gp-to-repo
 NHS_SERVICE=gp-to-repo
 
+####################################
+# Instance (Environment) Variables #
+####################################
+
 function check_env {
   if [[ -z "${NHS_ENVIRONMENT}" ]]; then
     echo "Must set NHS_ENVIRONMENT"
+    exit 1
+  fi
+}
+
+function check_nhs_service {
+  if [[ -z "${NHS_SERVICE}" ]]; then
+    echo "Must set NHS_SERVICE"
     exit 1
   fi
 }
@@ -22,6 +37,20 @@ function configure_local_envs {
   export GP2GP_URL="www.notreal.com"
   export REPOSITORY_URI=$IMAGE_REPO_NAME
 }
+
+function get_aws_secret {
+  secret_id=$1
+  json=$(aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id)
+  if [ $? != 0 ]; then
+    >&2 echo "Failed to obtain AWS secret: $secret_id"
+    exit 5
+  fi
+  echo $json | jq -r ".Parameter.Value"
+}
+
+#######################
+# Terraform Functions #
+#######################
 
 function tf_plan {
   operation=$1
@@ -50,6 +79,27 @@ function tf_apply {
   terraform output -json > tf-out.json
 }
 
+####################
+# Script Functions #
+####################
+
+function send_canary_update_message {
+  check_nhs_service
+  node scripts/send-canary-update.js $(npm outdated --parseable)
+}
+
+function configure_hangout_webhook {
+  export GOOGLE_CHAT_CANARY_WEBHOOK=$(get_aws_ssm_secret "/NHS/GoCD/prod/google-chat-canary-webhook")
+  if [ -z "${GOOGLE_CHAT_CANARY_WEBHOOK}" ]; then
+    echo "Unable to obtain GOOGLE_CHAT_CANARY_WEBHOOK from AWS"
+    exit 5
+  fi
+}
+
+############################
+# Docker Related Functions #
+############################
+
 function docker_login {
   echo Logging in to Amazon ECR...
   eval $(dojo -c Dojofile-infra "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
@@ -70,24 +120,34 @@ function configure_docker_repository_uri {
     export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
 }
 
-function get_aws_secret {
-  secret_id=$1
-  json=$(aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id)
-  if [ $? != 0 ]; then
-    >&2 echo "Failed to obtain AWS secret: $secret_id"
-    exit 5
-  fi
-  echo $json | jq -r ".Parameter.Value"
-}
+###########
+## TASKS ##
+###########
 
 command="$1"
 case "${command}" in
   _dep)
-      echo "Running NPM Audit ..."
+      npm install
       npm audit
       ;;
   dep)
       dojo "./tasks _dep"
+      ;;
+  _list_outdated)
+      npm install
+      npm outdated > outdated-dependencies.txt || send_canary_update_message
+      ;;
+  list_outdated)
+      configure_hangout_webhook
+      dojo "./tasks _list_outdated"
+      ;;
+  update_package_json)
+      dojo "npx npm-check-updates -u"
+      ;;
+  send_dead_canary_message)
+      check_nhs_service
+      configure_hangout_webhook
+      dojo "node scripts/send-canary-error.js"
       ;;
   _build)
       npm install
